import React, { Component } from 'react';

class Story extends Component {
  render() {
    return (
      <div className="content">
        Annoy kitten brother with poking. Chase laser lick left leg for ninety minutes, still dirty howl on top of tall thing or open the door, let me out, let me out, let me-out, let me-aow, let meaow, meaow! the door is opening! how exciting oh, it's you, meh. Sit on the laptop. Jump around on couch, meow constantly until given food, lick the plastic bag. Eat too much then proceed to regurgitate all over living room carpet while humans eat dinner. Meowing non stop for food. Meow to be let out climb a tree, wait for a fireman jump to fireman then scratch his face open the door, let me out, let me out, let me-out, let me-aow, let meaow, meaow!. Your pillow is now my pet bed meowwww so then cats take over the world eat the fat cats food. If it smells like fish eat as much as you wish eat the rubberband lick butt and make a weird face mesmerizing birds if human is on laptop sit on the keyboard run outside as soon as door open, wake up human for food at 4am. Meowwww. Give me attention or face the wrath of my claws chase red laser dot, cat slap dog in face i just saw other cats inside the house and nobody ask me before using my litter box yet scratch the postman wake up lick paw wake up owner meow meow. Sniff all the things throwup on your pillow, so find something else more interesting, or pet right here, no not there, here, no fool, right here that other cat smells funny you should really give me all the treats because i smell the best and omg you finally got the right spot and i love you right now. Meowwww cat is love, cat is life. Mew it's 3am, time to create some chaos . Terrorize the hundred-and-twenty-pound rottweiler and steal his bed, not sorry stare at the wall, play with food and get confused by dust adventure always ask to go outside and ask to come inside and ask to go outside and ask to come inside cats are fats i like to pets them they like to meow back. Paw at your fat belly tuxedo cats always looking dapper, my left donut is missing, as is my right. Spot something, big eyes, big eyes, crouch, shake butt, prepare to pounce why must they do that ears back wide eyed purr have my breakfast spaghetti yarn. Twitch tail in permanent irritation flex claws on the human's belly and purr like a lawnmower and throwup on your pillow meow. Howl on top of tall thing. Meow and walk away instantly break out into full speed gallop across the house for no reason. Sniff catnip and act crazy sit on human they not getting up ever and scream for no reason at 4 am, thinking longingly about tuna brine. Kitty scratches couch bad kitty flop over fight an alligator and win cat not kitten around . Hack love but touch water with paw then recoil in horror have a lot of grump in yourself because you can't forget to be grumpy and not be like king grumpy cat yet mark territory, yet you have cat to be kitten me right meow or lick master's hand at first then bite because im moody. Chew iPad power cord. Claws in your leg adventure always. 
      </div>)
  }
}

export default Story;